### ***Import Libraray***

In [5]:
import pandas as pd
import warnings
warnings.simplefilter(action='ignore',category=FutureWarning)

### ***Load Data***

In [6]:
df= pd.read_csv('../dataset/customer_shopping_behavior.csv')
df.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly
5,3583,23,Female,Shorts,Clothing,41.0,California,S,Beige,Summer,3.4,No,2-Day Shipping,No,15.0,PayPal,Annually
6,1135,62,Male,T-shirt,Clothing,81.0,Wisconsin,M,Brown,Summer,NaN,No,Express,Yes,2.0,Venmo,Every 3 Months
7,1411,61,Male,Hat,Accessories,93.0,Tennessee,M,Purple,Summer,4.0,No,Store Pickup,Yes,18.0,Debit Card,Annually
8,113,37,Male,Gloves,Accessories,65.0,Florida,M,Red,Spring,4.3,Yes,Free Shipping,Yes,28.0,PayPal,Bi-Weekly
9,166,42,Male,Handbag,Accessories,60.0,Kentucky,S,Yellow,Winter,2.8,Yes,Store Pickup,Yes,7.0,Cash,Monthly

### ***shape of data***

In [7]:
print('TOTAL NUMBER OF ROWS & COLUMN IN DATA:',df.shape)
print('TOTAL LENGHT OF DATA:',len(df))

TOTAL NUMBER OF ROWS & COLUMN IN DATA: (5050, 17)
TOTAL LENGHT OF DATA: 5050

### ***Numerical Description about Data***

In [8]:
df.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
count,5050.000000,5050.000000,5050,5050,5050,4494.000000,5050,4680,5050,5050,4449.000000,5050,5050,5050,4502.000000,5050,5050
unique,NaN,NaN,3,30,5,NaN,54,4,25,5,NaN,2,6,2,NaN,6,7
top,NaN,NaN,Male,Shirt,Clothing,NaN,New York,M,Black,Spring,NaN,No,Standard,No,NaN,Credit Card,Monthly
freq,NaN,NaN,3018,320,2130,NaN,337,1981,404,1280,NaN,3462,1213,2789,NaN,954,946
mean,2519.570891,44.150495,NaN,NaN,NaN,144.765236,NaN,NaN,NaN,NaN,3.668195,NaN,NaN,NaN,25.221901,NaN,NaN
std,1470.402964,15.282328,NaN,NaN,NaN,275.590101,NaN,NaN,NaN,NaN,0.865357,NaN,NaN,NaN,14.521635,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,10.120000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,0.000000,NaN,NaN
25%,1252.250000,31.000000,NaN,NaN,NaN,41.000000,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,13.000000,NaN,NaN
50%,2499.500000,44.000000,NaN,NaN,NaN,65.000000,NaN,NaN,NaN,NaN,3.700000,NaN,NaN,NaN,25.000000,NaN,NaN
75%,3740.750000,57.000000,NaN,NaN,NaN,89.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,38.000000,NaN,NaN
max,5099.000000,70.000000,NaN,NaN,NaN,1499.760000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,50.000000,NaN,NaN

### ***Information about data***

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             5050 non-null   int64
 1   Age                     5050 non-null   int64
 2   Gender                  5050 non-null   object
 3   Item Purchased          5050 non-null   object
 4   Category                5050 non-null   object
 5   Purchase Amount (USD)   4494 non-null   float64
 6   Location                5050 non-null   object
 7   Size                    4680 non-null   object
 8   Color                   5050 non-null   object
 9   Season                  5050 non-null   object
 10  Review Rating           4449 non-null   float64
 11  Subscription Status     5050 non-null   object
 12  Shipping Type           5050 non-null   object
 13  Discount Applied        5050 non-null   object
 14  Previous Purchases      4502 non-null   float64
 15  Payment Method          5050 non-null   object
 16  Frequency of Purchases  5050 non-null   object
dtypes: float64(3), int64(2), object(12)
memory usage: 670.8+ KB

In [10]:
pd.set_option('display.max_colwidth',None)
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

### ***Unique Values in item purchased & Category Column***

In [11]:
print(df['Item Purchased'].unique())
print("=================================================================")
print(df['Category'].unique())

['T-shirt' 'Sunglasses' 'Shirt' 'Gloves' 'Jewelry' 'Shorts' 'Hat'
 'Handbag' 'Shoes' 'Coat' 'Laptop' 'Hoodie' 'Phone' 'Jacket' 'Pants'
 'Backpack' 'Socks' 'Jeans' 'Bag' 'Belt' 'Watch' 'Headphones' 'Blouse'
 'Sandals' 'Skirt' 'Sweater' 'Scarf' 'Sneakers' 'Boots' 'Dress']
=================================================================
['Clothing' 'Accessories' 'Outerwear' 'Electronics' 'Footwear']

In [12]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories               [Sunglasses, Gloves, Jewelry, Hat, Handbag, Phone, Backpack, Belt, Bag, Headphones, Scarf, Watch, Shirt, Shoes, Laptop]
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone, Pants, Socks, Jeans, Bag, Blouse, Skirt, Sweater, Watch, Laptop, Dress, Headphones]
Electronics                                                                                 [Laptop, Phone, Watch, Bag, Shoes, Shirt, Headphones]
Footwear                                                                                                        [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                                                                          [Coat, Jacket]
Name: Item Purchased, dtype: object

### ***Mapping Items by Category***

In [13]:
correct_mapping = {
    # Clothing
    "T-shirt": "Clothing", "Shirt": "Clothing", "Shorts": "Clothing",
    "Hoodie": "Clothing", "Pants": "Clothing", "Socks": "Clothing",
    "Jeans": "Clothing", "Blouse": "Clothing", "Skirt": "Clothing",
    "Sweater": "Clothing", "Dress": "Clothing",

    # Accessories
    "Sunglasses": "Accessories", "Gloves": "Accessories",
    "Jewelry": "Accessories", "Hat": "Accessories",
    "Handbag": "Accessories", "Backpack": "Accessories",
    "Belt": "Accessories", "Scarf": "Accessories",
    "Bag": "Accessories",

    # Electronics
    "Laptop": "Electronics", "Phone": "Electronics",
    "Headphones": "Electronics", "Watch": "Electronics",

    # Footwear
    "Shoes": "Footwear", "Sandals": "Footwear",
    "Sneakers": "Footwear", "Boots": "Footwear",

    # Outerwear
    "Coat": "Outerwear", "Jacket": "Outerwear"
}

print(correct_mapping)

{'T-shirt': 'Clothing', 'Shirt': 'Clothing', 'Shorts': 'Clothing', 'Hoodie': 'Clothing', 'Pants': 'Clothing', 'Socks': 'Clothing', 'Jeans': 'Clothing', 'Blouse': 'Clothing', 'Skirt': 'Clothing', 'Sweater': 'Clothing', 'Dress': 'Clothing', 'Sunglasses': 'Accessories', 'Gloves': 'Accessories', 'Jewelry': 'Accessories', 'Hat': 'Accessories', 'Handbag': 'Accessories', 'Backpack': 'Accessories', 'Belt': 'Accessories', 'Scarf': 'Accessories', 'Bag': 'Accessories', 'Laptop': 'Electronics', 'Phone': 'Electronics', 'Headphones': 'Electronics', 'Watch': 'Electronics', 'Shoes': 'Footwear', 'Sandals': 'Footwear', 'Sneakers': 'Footwear', 'Boots': 'Footwear', 'Coat': 'Outerwear', 'Jacket': 'Outerwear'}

### ***Mapped(fit) the value in orignal dataset***

In [14]:
df['Category']=df['Item Purchased'].map(correct_mapping)
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories                 [Sunglasses, Gloves, Jewelry, Hat, Handbag, Backpack, Bag, Belt, Scarf]
Clothing       [T-shirt, Shirt, Shorts, Hoodie, Pants, Socks, Jeans, Blouse, Skirt, Sweater, Dress]
Electronics                                                      [Laptop, Phone, Watch, Headphones]
Footwear                                                          [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                            [Coat, Jacket]
Name: Item Purchased, dtype: object

### ***Missing Values***

In [15]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

### ***Fill misiing values***

In [16]:
print(df['Size'].unique())

['XL' 'M' 'L' 'S' nan]

In [17]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories                 [Sunglasses, Gloves, Jewelry, Hat, Handbag, Backpack, Bag, Belt, Scarf]
Clothing       [T-shirt, Shirt, Shorts, Hoodie, Pants, Socks, Jeans, Blouse, Skirt, Sweater, Dress]
Electronics                                                      [Laptop, Phone, Watch, Headphones]
Footwear                                                          [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                            [Coat, Jacket]
Name: Item Purchased, dtype: object

In [18]:
df.groupby('Category')['Size'].unique()

Category
Accessories    [M, L, S, XL, nan]
Clothing       [XL, M, S, L, nan]
Electronics    [nan, L, S, M, XL]
Footwear       [M, L, S, nan, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

### ***Fill Categories***

In [19]:
# Filled null values or replacing all values in the Electronics category
df.loc[df['Category']=='Electronics','Size']='Not Applicable'

# fILLED null values or replacing all values in the Accessories category
df.loc[df['Category']=='Accessories','Size']='Free Size'

# Filled null values or replacing all values in the Footwear category
df.loc[df['Category']=='Footwear','Size']='Not Available'

# Treating null values or replacing all values in the Clothing category
df.loc[(df['Category']=='Clothing') & (df['Size'].isnull()),'Size']=df[df['Category']=='Clothing']['Size'].mode()[0]

df.groupby('Category')['Size'].unique()

Category
Accessories         [Free Size]
Clothing          [XL, M, S, L]
Electronics    [Not Applicable]
Footwear        [Not Available]
Outerwear         [XL, L, S, M]
Name: Size, dtype: object

### ***Fill ReviewRating***

In [20]:
print('Mean of Review Rating:',df['Review Rating'].mean())
print('Median of Review Rating:',df['Review Rating'].median())
print('Mode of Review Rating:',df['Review Rating'].mode())

Mean of Review Rating: 3.668195100022477
Median of Review Rating: 3.7
Mode of Review Rating: 0    4.0
Name: Review Rating, dtype: float64

In [21]:
#Filling null values of Review Ratings with the mean of each Item Purchased
df['Review Rating']=df['Review Rating'].fillna(df.groupby('Item Purchased')['Review Rating'].transform('mean'))
df['Review Rating']=df['Review Rating'].round(2)
df['Review Rating'].tail(2)

5048    4.6
5049    3.3
Name: Review Rating, dtype: float64

### ***Fill Previous Purchases***

In [22]:
df['Previous Purchases']=df['Previous Purchases'].fillna(0)

### ***fill Purchased Amount USD***

In [23]:
df.groupby('Item Purchased')['Purchase Amount (USD)'].mean()

Item Purchased
Backpack       60.111111
Bag           735.773625
Belt           59.993902
Blouse         60.802326
Boots          62.616438
Coat           57.851852
Dress          62.168675
Gloves         60.550000
Handbag        57.987261
Hat            60.787097
Headphones    831.344565
Hoodie         58.059603
Jacket         56.777108
Jeans          60.456693
Jewelry        59.011494
Laptop        805.502027
Pants          59.005848
Phone         734.477349
Sandals        57.527607
Scarf          61.157233
Shirt         279.935608
Shoes         276.343790
Shorts         60.073620
Skirt          59.723270
Sneakers       59.551724
Socks          58.188679
Sunglasses     59.975610
Sweater        57.638554
T-shirt        63.093333
Watch         685.231471
Name: Purchase Amount (USD), dtype: float64

In [24]:
df['Purchase Amount (USD)']=df['Purchase Amount (USD)'].fillna(df.groupby('Item Purchased')['Purchase Amount (USD)'].transform('mean'))

In [25]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

### ***Finds Duplicate***

In [26]:
print('Total Duplicate values:',df.duplicated().sum())           # SUM OF DUPLICATE VALUE
df=df.drop_duplicates(subset=['Customer ID'],keep='first')       # REMOVE ALL DUPLICATE VALUES
print('Total Duplicate values after removing:',df.duplicated().sum())           # AGAIN PRINT SUM OF DUPLICATE VALUES AFTER DROP

Total Duplicate values: 50
Total Duplicate values after removing: 0

### ***Final COunt***

In [27]:
df.count()

Customer ID               5000
Age                       5000
Gender                    5000
Item Purchased            5000
Category                  5000
Purchase Amount (USD)     5000
Location                  5000
Size                      5000
Color                     5000
Season                    5000
Review Rating             5000
Subscription Status       5000
Shipping Type             5000
Discount Applied          5000
Previous Purchases        5000
Payment Method            5000
Frequency of Purchases    5000
dtype: int64

### ***Renaming Columns***

In [28]:
print('orignal columns name before renaming:\n',df.columns)

orignal columns name before renaming:
 Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Previous Purchases', 'Payment Method',
       'Frequency of Purchases'],
      dtype='object')

In [40]:
df.columns=df.columns.str.replace(" ","_")
df.columns=df.columns.str.lower()
#rename purchase_amount_(usd) column
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})
print('After renaming all columns name:\n',df.columns)

After renaming all columns name:
 Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

### ***Connect table to the database:***

In [ ]:
#install pyodbc sqlalchemy
pip install pyodbc sqlalchemy

Requirement already satisfied: pyodbc in c:\users\sumit\appdata\local\programs\python\python312\lib\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in c:\users\sumit\appdata\local\programs\python\python312\lib\site-packages (2.0.42)
Requirement already satisfied: greenlet>=1 in c:\users\sumit\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (3.2.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\sumit\appdata\roaming\python\python312\site-packages (from sqlalchemy) (4.12.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

### ***DATABASE CREATE***

In [36]:
import pyodbc

conn = pyodbc.connect(
    "Driver={SQL Server};"
    "Server=localhost\\SQLEXPRESS;"
    "Trusted_Connection=yes;",
    autocommit=True   # 🔥 ye important hai
)

cursor = conn.cursor()

cursor.execute("CREATE DATABASE customer_behavior_analysis")

print("✅ Database created successfully!")

conn.close()

✅ Database created successfully!

### ***Connect SQLAlChemy***

In [38]:
from sqlalchemy import create_engine
import urllib

server = r"localhost\SQLEXPRESS"
database = "customer_behavior_analysis"
driver = "ODBC Driver 17 for SQL Server"

connection_string = urllib.parse.quote_plus(
    f"DRIVER={{{driver}}};"
    f"SERVER={server};"
    f"DATABASE={database};"
    f"Trusted_Connection=yes;"
)

engine = create_engine(f"mssql+pyodbc:///?odbc_connect={connection_string}")

print("✅ Connected!")

✅ Connected!

In [ ]:
# create table
table_name = "customer_behavior_analysis"

df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

print("✅ Data inserted!")

C:\Users\sumit\AppData\Roaming\Python\Python312\site-packages\pandas\io\sql.py:1636: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

✅ Data inserted!